11 create event model
League-Of-Free-Internet/empty_project pull request #24
Opened 2024-05-20 16:36 UTC by chem1sto

Создал модель Events и админку к нему

2024-05-20 17:30 UTC, 1517mb requested changes
Нужно подумать, как сделать ссылками на изображения

2024-05-20 17:30 UTC, 1517mb commented on src/events/admin.py
> +        'name', 'date', 'text',
Здесь вместо text - short_text_preview

2024-05-20 17:30 UTC, 1517mb commented on src/events/models.py
> +    image = models.URLField(
У событий может быть много ссылок на изображения, а может быть одно, как раз сейчас думаю, как сделать

2024-05-20 17:45 UTC, chem1sto commented on src/events/admin.py
> +        'name', 'date', 'text',
Окей... Предлагаешь переименовать поле у модели?

2024-05-21 15:54 UTC, hydrospirt approved these changes

2024-05-21 15:54 UTC, hydrospirt commented on src/config/asgi.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
Мы же договаривались, что одинарная кавычка будет? 🙂🤔 Ну если, двойные пусть будут двойные

2024-05-21 15:59 UTC, chem1sto commented on src/config/asgi.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
Вопросы к black :black_heart:

2024-05-21 16:00 UTC, merged